#******************************************************************#
#                      GA-Spider Application                       #
#******************************************************************#
# Google Analytics — Beacons for tracking users                    #
# Application for tracking users through pictures and proxy links  #
# Copyright 2016 Vasilyuk Vasiliy <vasilyuk.vasiliy@gmail.com>     #
#******************************************************************#
#                   GitHub->https://git.io/vrsil                   #
#******************************************************************#

application: ga-spider
version: 1
runtime: php55
api_version: 1

handlers:
- url: /.*
  script: app.php